{
 "title": "Consensus",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "chain_name", "query": { "query": "label_values(chain_name)" } },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   },
   { "name": "role", "query": { "query": "label_values(role)" } },
   {
    "name": "interval",
    "label": "Aggregation Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Committed blocks per sec",
   "type": "timeseries",
   "description": "The rate of the committed round number.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile(0.5, rate(aptos_consensus_last_committed_round{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Committed successful txns per sec",
   "type": "timeseries",
   "description": "The rate of the committed transaction version.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quantile(0.5, rate(aptos_consensus_last_committed_version{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Participating voting power % in last 100 rounds",
   "type": "timeseries",
   "description": "Global statistics from the chain, all nodes that are caught up should have the same value.\n\nIf value goes below 80 it is concerning. if it goes below 72 it is a very bad.\n\nIt cannot go below 67%, because chain stops otherwise, and there is no data to show then.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "aptos_chain_health_participating_voting_power_last_100_rounds{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} * 100/aptos_chain_health_total_voting_power{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "participating voting power"
    }
   ]
  },
  {
   "title": "Transaction execution failed per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_committed_txns_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",state=\"failed\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{state}}"
    }
   ]
  },
  {
   "title": "Transaction execution retry per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_committed_txns_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",state=\"retry\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{state}}"
    }
   ]
  },
  {
   "title": "Round manager error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_error_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{state}}"
    }
   ]
  },
  { "title": "Latency breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Block creation to signed",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the leader signs it.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_tracing_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"signed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"signed\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to network receive",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the node receives it in consensus.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_tracing_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"network_received\"}[$interval]) / rate(aptos_consensus_block_tracing_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"network_received\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to round manager receive",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the node receives it in consensus.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_tracing_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"round_manager_received\"}[$interval]) / rate(aptos_consensus_block_tracing_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"round_manager_received\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to synced",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the node is synced and ready to execute.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_tracing_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"synced\"}[$interval]) / rate(aptos_consensus_block_tracing_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"synced\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to vote",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the node votes for it.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_tracing_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"voted\"}[$interval]) / rate(aptos_consensus_block_tracing_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"voted\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to QC aggregated",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the QC is aggregated by leader.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_tracing_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"qc_aggregated\"}[$interval]) / rate(aptos_consensus_block_tracing_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"qc_aggregated\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to QC received",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the node adds the QC.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_tracing_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"qc_added\"}[$interval]) / rate(aptos_consensus_block_tracing_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"qc_added\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to ordered",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the node ordered the block.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_tracing_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"ordered\"}[$interval]) / rate(aptos_consensus_block_tracing_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"ordered\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to executed",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the node executes the block.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_tracing_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"executed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"executed\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block creation to commit",
   "type": "timeseries",
   "description": "Duration between block generation time until the moment the node commits it.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_tracing_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"committed\"}[$interval]) / rate(aptos_consensus_block_tracing_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", stage=\"committed\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  { "title": "Internal call", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Process proposal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='process_proposal', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[$interval]) / rate(consensus_duration_count{op='process_proposal', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Process vote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='process_vote', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[$interval]) / rate(consensus_duration_count{op='process_vote', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Process sync info",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='process_sync_info', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='process_sync_info', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Process local timeout",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='process_local_timeout', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='process_local_timeout', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Verify message",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='verify_message', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='verify_message', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Process different epoch message",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='process_different_epoch_consensus_msg', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='process_different_epoch_consensus_msg', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Process epoch proof",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='process_epoch_proof', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='process_epoch_proof', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Process epoch retrieval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{op='process_epoch_retrieval', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{op='process_epoch_retrieval', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Await reconfig notification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='reconfig', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='reconfig', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Process block retrieval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='process_block_retrieval', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='process_block_retrieval', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Main Event Loop Current running function",
   "type": "graph",
   "description": "A sampled binary number indicating whether the node is currently in a function. (Useful when the node is stuck somewhere)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "consensus_gauge{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", op=~\".*_running\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}: {{op}}"
    }
   ]
  },
  {
   "title": "Buffer Manager Retry count",
   "type": "graph",
   "description": "A sampled binary number indicating whether the node is currently in a function. (Useful when the node is stuck somewhere)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "aptos_consensus_buffer_manager_retry_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}: {{op}}"
    }
   ]
  },
  { "title": "RoundState", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Current Round",
   "type": "timeseries",
   "description": "The current round consensus is at, the rate of this is roughly Committed blocks per sec.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_consensus_current_round{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "QC round per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_qc_rounds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Timeout rounds per sec",
   "type": "timeseries",
   "description": "The total number of rounds that have timeout certificate.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_timeout_rounds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total local timeout",
   "type": "timeseries",
   "description": "The total number a single node has timeout locally. When 2f+1 nodes have local timeout for the same round, a timeout round is formed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_timeout_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Current Round timeout value",
   "type": "timeseries",
   "description": "The duration of a single round until it generates local timeout.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aptos_consensus_round_timeout_s{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  { "title": "EpochState", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Current Epoch",
   "type": "timeseries",
   "description": "The current epoch number the node is in, the number is bumped with reconfiguration event like key rotation, validator set change etc.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_consensus_epoch{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Number of validators",
   "type": "timeseries",
   "description": "Number of validators for the current epoch.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_consensus_current_epoch_validators{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total voting power",
   "type": "timeseries",
   "description": "Total voting power of the current epoch.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_total_voting_power{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} / 100000000",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  { "title": "BlockStore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Pending blocks",
   "type": "timeseries",
   "description": "Pending blocks in the block tree.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_consensus_num_blocks_in_tree{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} - 1",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Transactions per block",
   "type": "timeseries",
   "description": "The average number of transactions of a block, can impact the execution time and overall latency.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_num_txns_per_block_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_consensus_num_txns_per_block_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Wait duration per sec",
   "type": "timeseries",
   "description": "Total time the node has to wait before inserting the block",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_wait_duration_s_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Pending blocks in pipeline",
   "type": "timeseries",
   "description": "Pending blocks in the pipeline",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_consensus_num_blocks_in_pipeline{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Back pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "consensus_gauge{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", op=\"back_pressure\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Sync only",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "consensus_gauge{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", op=\"sync_only\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  { "title": "External call", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Execute block Latency",
   "type": "timeseries",
   "description": "The average time to execute a block.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='execute_block', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='execute_block', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Commit block Latency",
   "type": "timeseries",
   "description": "The average time to commit blocks (may commit more than 1 in a single call).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='commit_block', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='commit_block',  kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Safety rules Latency",
   "type": "timeseries",
   "description": "The average latency of talking to safety rules (of all calls).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='safety_rules', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='safety_rules', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Pull txn Latency",
   "type": "timeseries",
   "description": "The average latency of pulling the txn from mempool.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='pull_txn', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='pull_txn', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Failed txn notify mempool Latency",
   "type": "timeseries",
   "description": "The average latency of notifying mempool about failed transactions.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='notify_mempool', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='notify_mempool', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Notify state sync Latency",
   "type": "timeseries",
   "description": "The average latency of notifying state sync of committed txn.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='notify_state_sync', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='notify_state_sync', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "State sync count per sec",
   "type": "timeseries",
   "description": "The total count of call to sync to.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='sync_to', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total time spent on state sync",
   "type": "timeseries",
   "description": "The total time spent in the external sync_to function.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='sync_to', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block retrieval count per sec",
   "type": "timeseries",
   "description": "The total number of block retrieval the node sends. It's required when the node is missing some ancestors of the block to be executed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(consensus_duration_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='block_retrieval', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total time spent on block retrieval",
   "type": "timeseries",
   "description": "Total time spent in retrieval the blocks from peers. (This is blocking RPC call)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "consensus_duration_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", op='block_retrieval', kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  { "title": "Proposer Election", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 } },
  {
   "title": "Proposals rate",
   "type": "timeseries",
   "description": "The proposal rate of the node, indicating how many times it becomes leaders.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_proposals_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Nil block per sec",
   "type": "timeseries",
   "description": "The total number the node votes on a NIL block when the round timeout. (when the proposer doesn't send proposal in time).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_vote_nil_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Message queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network -> Consensus Enqueue rate",
     "type": "timeseries",
     "description": "The channel metrics related to network layer to consensus.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_pending_network_events{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"enqueued\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Network -> Consensus Dequeue rate",
     "type": "timeseries",
     "description": "The channel metrics related to network layer to consensus.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_pending_network_events{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"dequeued\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Network -> Consensus Dropped rate",
     "type": "timeseries",
     "description": "The channel metrics related to network layer to consensus.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_pending_network_events{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"dropped\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Block retrieval Enqueue rate",
     "type": "timeseries",
     "description": "The channel metrics related to consensus block retrieval (dedicated channel for the rpc).",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_block_retrieval_channel_msgs_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"enqueued\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Block retrieval Dequeue rate",
     "type": "timeseries",
     "description": "The channel metrics related to consensus block retrieval (dedicated channel for the rpc).",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_block_retrieval_channel_msgs_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"dequeued\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Block retrieval Dropped rate",
     "type": "timeseries",
     "description": "The channel metrics related to consensus block retrieval (dedicated channel for the rpc).",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_block_retrieval_channel_msgs_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"dropped\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Epoch manager Enqueue rate",
     "type": "timeseries",
     "description": "The channel metrics related to consensus network -> main loop. (It only keeps one message per peer per type).",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_channel_msgs_count{chain_name=~\"$chain_name\", namespace=\"$namespace\", state=\"enqueued\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Epoch manager Dequeue rate",
     "type": "timeseries",
     "description": "The channel metrics related to consensus network -> main loop. (It only keeps one message per peer per type).",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_channel_msgs_count{chain_name=~\"$chain_name\", namespace=\"$namespace\", state=\"dequeued\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Epoch manager Dropped rate",
     "type": "timeseries",
     "description": "The channel metrics related to consensus network -> main loop. (It only keeps one message per peer per type).",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_channel_msgs_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"dropped\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Round manager Enqueue rate",
     "type": "timeseries",
     "description": "The channel metrics related to consensus network -> main loop. (It only keeps one message per peer per type).",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_round_manager_msgs_count{chain_name=~\"$chain_name\", namespace=\"$namespace\", state=\"enqueued\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Round manager Dequeue rate",
     "type": "timeseries",
     "description": "The channel metrics related to consensus network -> main loop. (It only keeps one message per peer per type).",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_round_manager_msgs_count{chain_name=~\"$chain_name\", namespace=\"$namespace\", state=\"dequeued\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Round manager Dropped rate",
     "type": "timeseries",
     "description": "The channel metrics related to consensus network -> main loop. (It only keeps one message per peer per type).",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_round_manager_msgs_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"dropped\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Buffer manager Enqueue rate",
     "type": "timeseries",
     "description": "The channel metrics related to consensus network -> main loop. (It only keeps one message per peer per type).",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_buffer_manager_msgs_count{chain_name=~\"$chain_name\", namespace=\"$namespace\", state=\"enqueued\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$__rate_interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Buffer manager Dequeue rate",
     "type": "timeseries",
     "description": "The channel metrics related to consensus network -> main loop. (It only keeps one message per peer per type).",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_buffer_manager_msgs_count{chain_name=~\"$chain_name\",namespace=\"$namespace\", state=\"dequeued\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Buffer manager Dropped rate",
     "type": "timeseries",
     "description": "The channel metrics related to consensus network -> main loop. (It only keeps one message per peer per type).",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_buffer_manager_msgs_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", state=\"dropped\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Pending self message",
     "type": "timeseries",
     "description": "The pending messages in the self message queue (for proposal and vote) and timeout queue (for local timeout).",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aptos_consensus_pending_self_messages{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Pending round local timeouts",
     "type": "timeseries",
     "description": "The pending messages in the self message queue (for proposal and vote) and timeout queue (for local timeout).",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aptos_consensus_pending_round_timeouts{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Pending state sync notification",
     "type": "timeseries",
     "description": "The pending messages in the self message queue (for proposal and vote) and timeout queue (for local timeout).",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aptos_consensus_pending_state_sync_notification{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
      }
     ]
    },
    {
     "title": "Consensus Message Sent",
     "type": "timeseries",
     "description": "The number of messages sent group by types",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_sent_msgs_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{type}}"
      }
     ]
    },
    {
     "title": "Consensus Message Received",
     "type": "timeseries",
     "description": "The number of messages received group by types",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aptos_consensus_received_msgs_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{type}}"
      }
     ]
    }
   ]
  },
  { "title": "Collected votes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 } },
  {
   "title": "collected voting power for proposal",
   "type": "timeseries",
   "description": "Voting power of all votes for the same ledger info collected by a proposer",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 170 },
   "targets": [
    {
     "expr": "rate(aptos_proposer_collected_most_voting_power_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])/rate(aptos_proposer_collecting_round_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])/aptos_total_voting_power{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "collected voting power for conflicting",
   "type": "timeseries",
   "description": "Voting power of all votes for all other (conflicting) ledger infos collected by a proposer",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 170 },
   "targets": [
    {
     "expr": "rate(aptos_proposer_collected_conflicting_voting_power_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])/rate(aptos_proposer_collecting_round_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])/aptos_total_voting_power{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "collected voting power for timeout votes",
   "type": "timeseries",
   "description": "Voting power of timeout votes collected by a proposer",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 170 },
   "targets": [
    {
     "expr": "rate(aptos_proposer_collected_timeout_voting_power_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])/rate(aptos_proposer_collecting_round_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])/aptos_total_voting_power{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Participating in consensus",
   "type": "timeseries",
   "description": "Participating in consensus in leader election window (either voted in last num_validators rounds, or proposed in last 10*num_validators rounds)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 178 },
   "targets": [
    {
     "expr": "clamp_max(aptos_committed_votes_in_window{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} + aptos_committed_proposals_in_window{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}, 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal failure rate",
   "type": "timeseries",
   "description": "Proposal failure rate in leader election window. Value goes back to 0 once node is not asked to propose at all in the window",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 178 },
   "targets": [
    {
     "expr": "aptos_failed_proposals_in_window{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} / clamp_min(aptos_failed_proposals_in_window{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} + aptos_committed_proposals_in_window{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}, 1)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Participating voting power % in consensus",
   "type": "timeseries",
   "description": "Global statistics from the chain, all nodes that are caught up should have the same value.\n\nIf value goes below 80 it is concerning. if it goes below 72 it is a very bad.\n\nIt cannot go below 67%, because chain stops otherwise, and there is no data to show then.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 186 },
   "targets": [
    {
     "expr": "quantile(0.5, aptos_chain_health_participating_voting_power_last_10_rounds{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} * 100/aptos_chain_health_total_voting_power{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "last 10 rounds"
    },
    {
     "expr": "quantile(0.5, aptos_chain_health_participating_voting_power_last_30_rounds{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} * 100/aptos_chain_health_total_voting_power{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "last 30 rounds"
    },
    {
     "expr": "quantile(0.5, aptos_chain_health_participating_voting_power_last_100_rounds{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} * 100/aptos_chain_health_total_voting_power{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "last 100 rounds"
    },
    {
     "expr": "quantile(0.5, aptos_chain_health_participating_voting_power_last_300_rounds{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} * 100/aptos_chain_health_total_voting_power{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "last 300 rounds"
    }
   ]
  },
  {
   "title": "Participating nodes % in consensus",
   "type": "timeseries",
   "description": "Global statistics from the chain, all nodes that are caught up should have the same value.\n\nIf value goes below 80 it is concerning. if it goes below 72 it is a very bad.\n\nIt cannot go below 67%, because chain stops otherwise, and there is no data to show then.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 186 },
   "targets": [
    {
     "expr": "quantile(0.5, aptos_chain_health_participating_num_validators_last_10_rounds{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} * 100/aptos_chain_health_total_num_validators{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "last 10 rounds"
    },
    {
     "expr": "quantile(0.5, aptos_chain_health_participating_num_validators_last_30_rounds{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} * 100/aptos_chain_health_total_num_validators{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "30"
    },
    {
     "expr": "quantile(0.5, aptos_chain_health_participating_num_validators_last_100_rounds{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} * 100/aptos_chain_health_total_num_validators{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "last 100 rounds"
    },
    {
     "expr": "quantile(0.5, aptos_chain_health_participating_num_validators_last_300_rounds{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"} * 100/aptos_chain_health_total_num_validators{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "last 300 rounds"
    }
   ]
  }
 ]
}